name: Update Native Library

on:
  workflow_dispatch:

jobs:
  update-native-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download native library artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: PatrickKocken/runelite-touch-bar-native-library
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: libJavaTouchBar.dylib
          
      - name: Download native library checksum artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: PatrickKocken/runelite-touch-bar-native-library
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: checksum.txt
          
      - name: Check checksum output
        run: |
            cat checksum.txt
            shasum -a 512 -c checksum.txt
        
      - name: Remove old release
        uses: JesseTG/rm@v1.0.3
        with:
          path: src/main/resources/lib/libJavaTouchBar.dylib
        
      - name: Download latest release
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          repo: 'PatrickKocken/runelite-touch-bar-native-library'
          file: 'libJavaTouchBar.dylib'
          target: 'src/main/resources/lib/libJavaTouchBar.dylib'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push library
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          default_author: github_actions
          message: 'Update native library'
          new_branch: github-actions/update-native-library
          
      - name: Create pull request with library
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: github-actions/update-native-library
          target_branch: master
          reviewer: patrickkocken
          assignee: patrickkocken
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: true
