name: Update Native Library

on:
  workflow_dispatch:

jobs:
  update-native-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Remove old release
        uses: JesseTG/rm@v1.0.3
        with:
          path: src/main/resources/lib/libJavaTouchBar.dylib
        
      - name: Download latest release
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          repo: 'PatrickKocken/runelite-touch-bar-native-library'
          file: 'libJavaTouchBar.dylib'
          target: 'src/main/resources/lib/libJavaTouchBar.dylib'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push library
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          default_author: github_actions
          message: 'Update native library'
          new_branch: github-actions/update-native-library
          
      - name: Create pull request with library
        uses: peter-evans/create-pull-request@v4
        with:
          base: development
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: github-actions/update-native-library
          delete-branch: true
          title: '[Github Actions] Update native library'
          assignees: PatrickKocken
          reviewers: PatrickKocken
