name: Update Native Library

on:
  workflow_dispatch:

jobs:
  update-native-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download native library artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: PatrickKocken/runelite-touch-bar-native-library
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: libJavaTouchBar.dylib
          rename: libJavaTouchBar.zip
          
      - name: Download native library checksum artifact
        uses: bettermarks/action-artifact-download@0.3.0
        with:
          repo: PatrickKocken/runelite-touch-bar-native-library
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: checksum.txt
          rename: checksum.zip
          
      - name: Check checksum output
        run: |
            unzip checksum.zip && rm checksum.zip
            unzip libJavaTouchBar.zip && rm libJavaTouchBar.zip
            cat checksum.txt
            shasum -a 512 libJavaTouchBar.dylib
            shasum -a 512 -c checksum.txt
        
      - name: Update native library release
        run: |
            rm src/main/resources/lib/libJavaTouchBar.dylib
            rm src/main/resources/lib/checksum.txt
            mv libJavaTouchBar.dylib src/main/resources/lib/
            mv checksum.txt src/main/resources/lib/
        
      - name: Commit and push new native library
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          default_author: github_actions
          message: 'Update native library'
          new_branch: github-actions/update-native-library
          
      - name: Create pull request with new native library
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: github-actions/update-native-library
          target_branch: master
          reviewer: patrickkocken
          assignee: patrickkocken
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: true
